### ISSUE TITLE
[1.18.2] It looks like this is breaking the game due to a possibly mismatch between versions of this & FTB Quests

### ISSUE THREAD

**Issue by vizthex123** [AHilyard/QuestPlaques#5]
I've had a few players of my modpack report this issue, and I think it's mainly FTB Quests, but they don't have an issue tracker so let's hope this mod can fix it.

But, Quest Plaques is also mentioned in the logs just a line or two below FTB Quests.

Here's his log file:
[latest.log](https://github.com/AHilyard/QuestPlaques/files/9023727/latest.log)

If I get any more reports with this same issue, I'll toss them in here.

And if Quest Plaques isn't doing anything, sorry for the pointless report - but as I said, I'm out of options since FTB Quests hasn't got an issue tracker.

**Comment by AHilyard** [comment]
This issue is likely fixable from either Quest Plaques or FTB Quests.  From what I can tell from the log file, a quest is being completed before FTB Quests is fully loaded.  Do you know if you have any quests that could be completed right when a player logs in or starts the game?

**Comment by AHilyard** [comment]
Actually I found that I have a test build already that is intended to fix this, since it has been reported before, but it hasn't been tested.  I don't have a set up to test it currently, would you be able to test this version?

[QuestPlaques-1.18.2-1.0.3.zip](https://github.com/AHilyard/QuestPlaques/files/9025295/QuestPlaques-1.18.2-1.0.3.zip)

**Comment by vizthex123** [comment]
I don't have any, no.

And I'll see if we can, yeah.

**Comment by vizthex123** [comment]
Alrighty, I've tested it & it worked. Was able to load my world too, which was breaking cuz of this issue.

**Comment by AHilyard** [comment]
Awesome, thank you for testing.  I'll get this fix released officially soon.

**Comment by vizthex123** [comment]
> Awesome, thank you for testing. I'll get this fix released officially soon.

Yeah, thanks for fixing it. I suppose I'll let you know if it breaks again.

Do you have an ETA for "soon"? Was hoping to get it in my pack's next update, and people keep reporting the same crash.

**Comment by AHilyard** [comment]
Well, this is embarrassing.  The update was released a couple days after your last message but I never updated this issue, my bad.  Closing now...

**Comment by vizthex123** [comment]
lol it's ok. Thanks again for fixing it.
